# Generated by Django 5.0.7 on 2024-07-18 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uidString', models.CharField(max_length=255, unique=True)),
                ('retailer', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('total', models.FloatField()),
                ('total_points', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rouletteApp.reciept')),
            ],
        ),
    ]
